### ISSUE TITLE
- error Conflict: Multiple assets emit different content to the same filename koffi.node

### ISSUE THREAD

**Issue by emanueleecho** [eisberg-labs/nextjs-node-loader#18]
hey i'm getting this error
- error Conflict: Multiple assets emit different content to the same filename koffi.node, 
i'm coding in nextjs ambient, that's my config
import os from 'os';

export default {
    reactStrictMode: false,
    env: {
        BASE_URL: process.env.BASE_URL,
    },
    webpack: (config, { dev, isServer, webpack, nextRuntime }) => {
        // Trova la regola esistente per i file .node, se presente
        const existingNodeRule = config.module.rules.find((rule) =>
            rule.test instanceof RegExp && /\.node$/.test(rule.test.source)
        );
        console.log(existingNodeRule);

        if (existingNodeRule) {
            console.log("C'è");
            // Modifica la regola esistente invece di aggiungerne una nuova
            existingNodeRule.use.push({
                loader: "nextjs-node-loader",
                options: {
                    flags: os.constants.dlopen.RTLD_NOW,
                    outputPath: config.output.path,
                },
            });
        } else {
            console.log("Non c'è");

            // Se non esiste una regola esistente, crea una nuova regola
            config.module.rules.push({
                test: /\.node$/,
                use: [
                    {
                        loader: "nextjs-node-loader",
                        options: {
                            flags: os.constants.dlopen.RTLD_NOW,
                            outputPath: config.output.path,
                        },
                    },
                ],
            });
        }

        return config;
    },
};

**Comment by amarjanica** [comment]
Hi, thanks for reporting the issue. I need a minimum reproducible example to help me debug this.

**Comment by emanueleecho** [comment]
yea, that's my next.config.js
```javascript
import os from 'os';
import path from 'path';
import { fileURLToPath } from 'url';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export default {
    reactStrictMode: false,
    env: {
        BASE_URL: process.env.BASE_URL,
    },
    webpack: (config, { dev, isServer, webpack, nextRuntime }) => {
        // Trova la regola esistente per i file .node, se presente
        console.log(config.output.path);
        console.log(os.constants.dlopen.RTLD_NOW);
        config.module.rules.push({
            test: /\.node$/,
            use: [
                {
                    loader: "nextjs-node-loader",
                    options: {
                        flags: os.constants.dlopen.RTLD_NOW,
                        outputPath: config.output.path
                    },
                },
            ],
        });

        return config;
    },
};

``` 

and the part where i import koffi is here

```typescript
import koffi from 'koffi'
import { fileURLToPath } from 'url';
import path from "path"
import { CookieJar, Cookie } from 'tough-cookie';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
import fs from "fs"
export class TLS_Client {
    jar: CookieJar | any
    tls: any
    constructor(props?: any) {
        if (props && props.enable_cookies) {
            this.jar = new CookieJar();
        }
        console.log("Getting tls");
        this.tls = this.initTLS();
    }
    initTLS() {
        let tlsLib = process.platform.includes('win') ? path.join(__dirname, './tls-client-windows-64-0.9.1.dll') : path.join(__dirname, './tls-client-linux-ubuntu-amd64-0.9.1.so')
        console.log(tlsLib);
        const lib = koffi.load(tlsLib)
        return {
            request: lib.func("request", "string", ["string"]),
            getCookiesFromSession: lib.func("getCookiesFromSession", "string", ["string"]),
            freeAll: lib.func("freeAll", "string", ["string"]),
            freeSession: lib.func("freeSession", "string", ["string"]),
        }
    }
}
```

**Comment by emanueleecho** [comment]
before koffi i was trying to use ffi-napi that's an other lib used to load compiled c+ libs to node but it was not importable to nextjs due to webpack incompatibily, koffi have not this problem and people use it also with electron

**Comment by amarjanica** [comment]
Ok, I need more information, package versions. Post me a minimal repro github repository which I can clone and start debugging the issue. My first guess is koffi is missing suffixes for different platforms as the error message says `Multiple assets emit different content to the same filename koffi.node`. I can't start working on this until Monday. I also have to push a fix #17, that's why I was interested in nextjs version.

**Comment by emanueleecho** [comment]
okay, i created a repo for u to try it out, that's the url https://github.com/emanueleecho/test-nextjs-node-loader
just "npm i" "npm run dev" and open http://localhost:3000/api/v1/test if u have any question that can help lmk :)
thank you again for your time!

**Comment by amarjanica** [comment]
check the repository settings and make it public, I get a 404 not found.

**Comment by emanueleecho** [comment]
done

**Comment by emanueleecho** [comment]
i've just tried and seems that is working correctly! will update u better with more tests soon, thank you!!
