### ISSUE TITLE
can not find module

### ISSUE THREAD

**Issue by imding** [eisberg-labs/nextjs-node-loader#2]
hi, I installed this package and followed the instructions but still getting "Cannot find module '...'" error.

In your README.MD it says 
```js
import module from node-module;
```
I am not sure what the "node-module" equivalent path in my project is, but I've tried using the root of my neon repo, and also the exact path that points to the .node file, neither works for me.

And for some reason, I can not access `dlopen.RTLD_NOW` on my `os.constants` object.

my project looks like this:

```md
root
|-- apps
    |-- web
        |-- next.config.mjs
        |-- src
            |-- pages
                |-- _app.tsx          <-- I want to import & call lib.rs functions here
|-- packages
    |-- rs-lib
        |-- index.node
        |-- src
            |-- lib.rs
```

Thanks in advance for your help.

**Comment by amarjanica** [comment]
Hi, were you able to solve this, that's why you closed the issue?
