### ISSUE TITLE
`os is not defined` in next.config.js

### ISSUE THREAD

**Issue by kenirwin** [eisberg-labs/nextjs-node-loader#31]
I've installed nextjs-node-loader and used the next.config.js file shown in the documentation, but when I try to build my project I get an error re: this line in the config:
`flags: os.constants.dlopen.RTLD_NOW,`

```
Build error occurred
ReferenceError: os is not defined
```
Should I be defining os somehow?

**Comment by archnode** [comment]
This is a node module you can import. See: https://nodejs.org/api/os.html#os

**Comment by amarjanica** [comment]
You don't need to use the flags, it's just an example pulled from [https://github.com/eisberg-labs/nextjs-node-loader/blob/main/examples/next-13-koffi/next.config.js](https://github.com/eisberg-labs/nextjs-node-loader/blob/main/examples/next-13-koffi/next.config.js). As @archnode said, it's a dependency that you need to install if you need it.
