### ISSUE TITLE
nodejs-polars

### ISSUE THREAD

**Issue by elge70** [eisberg-labs/nextjs-node-loader#32]
I have started a discussion on nodejs-polars (https://www.npmjs.com/package/nodejs-polars)

https://github.com/vercel/next.js/discussions/63884

Could you please have a look.

**Comment by amarjanica** [comment]
I'm sorry but I can take a look only when I have enough information on your issue.
I need a more descriptive issue report, not just pasting me the link on another opened issue on another repository.
I need a reproducible, versions, I don't want to spend time on investigating a new library just to solve an issue related to it.

I just [pushed an example with Next 14](https://github.com/eisberg-labs/nextjs-node-loader/tree/main/examples/next-14-el-slugify), you can fork and create a reproducible on that.
Then open a new issue and add a link to the repository so I can take a look.
