### ISSUE TITLE
[BUG] Error: nextjs-node-loader: Module did not self-register: robotjs

### ISSUE THREAD

**Issue by antonbrams** [eisberg-labs/nextjs-node-loader#48]
**Describe the bug**
robotjs did compiled for node successfully and at the first page compilation it works flawlessly but as i change something in my react sourcecode (server or client side), page recompiles and throws the error multiple times

```
Error: nextjs-node-loader:
Error: Module did not self-register: '.../root_directory/.next/server/robotjs.node'.
...
at async Server.requestListener (.../root_directory/node_modules/next/dist/server/lib/start-server.js:141:13) {
  digest: '246830862',
  page: '/0/0'
}
```

as i resave the next.config.js (apparently the whole project restarts) and everything starts to function again until the next hot reload

Which version of Next.js? 
"next": "^14.2.11",

Which version of nextjs-node-loader?
"nextjs-node-loader": "^1.1.5",

**To Reproduce**
Steps to reproduce the behavior or even better. Share me a link to repository with reproducable:
see the bug description

**Comment by antonbrams** [comment]
thanks for help! your reply was so quick <3

p.s. in case somebody waisted 26 hours on debugging as well... my solution was to downgrade next from 14.2.11 to 14.2.3

**Comment by amarjanica** [comment]
I'm sorry I didn't respond at time, but I don't appreciate the sarcastic tone in your last reply. 
You have to realize that I'm the sole maintainer of this repository and that you might not get an instant reply. 
I try my best to keep up with issues, but with the volume of notifications and my other responsibilities, some things can get missed. I appreciate your patience and thank you for sharing your workaround.
I also don't know when I'll have time to take a better look, you're welcome to contribute to this repository.

**Comment by lsafd** [comment]
I just want to add that I had the exact same issue with multiple modules (keytar, msnodesqlv8, etc.), downgrading to next 14.2.3 (didn't try other versions) fixed this issue, seems that something changed in the intervening versions that breaks nextjs-node-loader

Just wanted to add a big thank you to @amarjanica for maintaining the repo

**Comment by amarjanica** [comment]
You're welcome, @lsafd. I'll try to make time by the end of the week to look into this and I'll report here what I find. If anyone else wants to give it a try in the meantime, feel free to jump in

**Comment by amarjanica** [comment]
I believe this is related to #45 , but never got a response back. Something in webpack changed. What previously worked as:
```
    config.module.rules.push({
      test: /\.node$/,
      use: [
        {
          loader: 'nextjs-node-loader',
          options: {
            flags: os.constants.dlopen.RTLD_NOW,
            outputPath: config.output.path
          },
        },
      ],
    });
```
is now a 
```
 config.module.rules.push({
      test: /.+.node$/ig,
      use: [
        {
          loader: 'nextjs-node-loader',
          options: {
            flags: os.constants.dlopen.RTLD_NOW,
            outputPath: config.output.path
          },
        },
      ],
    });
```
Note the regex pattern change. Please let me know if it works for you @lsafd and @antonbrams

**Comment by amarjanica** [comment]
@lsafd @antonbrams try the 1.1.8 version. I don't know exactly what was the issue, but bumped all the dependencies and updated my example/next-14. when you run it, go to `/api/robotjs`, you should get a mouse position response. also added next-14 example build to the ci, to avoid "it works on my machine".
dunno, maybe the dependencies bump helped

**Comment by lsafd** [comment]
@amarjanica Let me know if I should create a new issue, but I am still having issues with msnodesqlv8. Here is a repo that should make recreating it easy https://github.com/lsafd/nextjs-node-loader-msnodesqlv8 (just load / on different versions of next).

This has taken me down a bit of a rabbit hole. I will say this is an area where I have little expertise, but I tried the following https://github.com/TimelordUK/todo-with-nextjs_msnodesqlv8 which works fine (without even using nextjs-node-loader). I then tried to copy the setup with the app router where doing a require or import failed. Could you explain / link me to some materials about why this is the case? I find this topic very interesting but am struggling to find documentation for changes.

**Comment by amarjanica** [comment]
Thanks for sharing the repo. Little background on this loader:
This is a plugin which calls `process.dlopen`, which is a low-level function in Node.js used to load and dynamically link native modules. Plugin was adapted from [https://github.com/webpack-contrib/node-loader](https://github.com/webpack-contrib/node-loader) because a solution is specific to nextjs and how it handles assets.
Key is to get `process.dlopen` work with the correct path to the native module.
You got it, this is broken in 14.2.14.

It's hard to pinpoint where's the issue, but when debugging it, take a look at the require part in `.next/server/app/api/your_route_that_requests_native_module/route.js`.

In previous versions, path to native module was correct.

In >14.2.14, loader works up to a point that it puts .node modules in `.next/server/chunks` and I can also console.log the correct require path to native modules. But the `route.js` require path is wrong.
Currently I have zero idea except that I'm getting suspicious that some other webpack loader is causing this.
Zero idea

**Comment by amarjanica** [comment]
hey @lsafd and @antonbrams, solution is to add:
```
  experimental: {
    serverComponentsExternalPackages: ["yournodepackage"],
  },
```
A similar issue was https://github.com/yisibl/resvg-js/issues/315#issuecomment-2395408012
I guess there's no longer need for this loader.

**Comment by lsafd** [comment]
Works for me! Appreciate the help.

**Comment by amarjanica** [comment]
I'm closing the issue as completed. Solution for a module built with neon bindings is slightly different. Instructions are in Readme.md. Thanks for reporting the issue
